
package webservice.processRoute;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* ZPP_TC_SAP_006 service = new ZPP_TC_SAP_006();
* ZPPTCSAP006 portType = service.getZPPTCSAP006();
* portType.zppTCSAP006(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "ZPP_TC_SAP_006", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_006.wsdl")
public class ZPPTCSAP006_Service extends Service {

	private final static URL ZPPTCSAP006_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(webservice.processRoute.ZPPTCSAP006_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.processRoute.ZPPTCSAP006_Service.class.getResource(".");
			url = new URL(baseUrl,
					"file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_006.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_006.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ZPPTCSAP006_WSDL_LOCATION = url;
	}

	public ZPPTCSAP006_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZPPTCSAP006_Service() {
		super(ZPPTCSAP006_WSDL_LOCATION, new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_006"));
	}

	/**
	 * 
	 * @return returns ZPPTCSAP006
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_006")
	public ZPPTCSAP006 getZPPTCSAP006() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_006"), ZPPTCSAP006.class);
	}

	/**
	 * 
	 * @return returns ZPPTCSAP006
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_006_soap12")
	public ZPPTCSAP006 getZPPTCSAP006Soap12() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_006_soap12"),
				ZPPTCSAP006.class);
	}

}
