
package integration.base.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import integration.base.bom.TABLEOFZPPTCI005;
import integration.base.bom.TABLEOFZPPTCO005;
import integration.base.classify.TABLEOFZPPTCI003;
import integration.base.classify.TABLEOFZPPTCO003;
import integration.base.feature.TABLEOFZPPTCI002;
import integration.base.feature.TABLEOFZPPTCO002;
import integration.base.masterMaterial.TABLEOFZPPTCI001;
import integration.base.masterMaterial.TABLEOFZPPTCO001;
import integration.base.processRoute.TABLEOFZPPTCI006;
import integration.base.processRoute.TABLEOFZPPTCO006;
import integration.base.productAttributes.TABLEOFZPPTCI007;
import integration.base.productAttributes.TABLEOFZPPTCO007;
import integration.base.relevance.TABLEOFZPPTCI004;
import integration.base.relevance.TABLEOFZPPTCO004;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SAPForTCProxyPortType", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public interface SAPForTCProxyPortType {

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_001", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_001:ZPP_TC_SAP_001Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_001", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP001")
	@ResponseWrapper(localName = "ZPP_TC_SAP_001Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP001Response")
	public void zppTCSAP001(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI001> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO001> output);

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_002", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_002:ZPP_TC_SAP_002Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_002", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP002")
	@ResponseWrapper(localName = "ZPP_TC_SAP_002Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP002Response")
	public void zppTCSAP002(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI002> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO002> output);

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_003", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_003:ZPP_TC_SAP_003Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_003", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP003")
	@ResponseWrapper(localName = "ZPP_TC_SAP_003Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP003Response")
	public void zppTCSAP003(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI003> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO003> output);

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_004", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_004:ZPP_TC_SAP_004Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_004", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP004")
	@ResponseWrapper(localName = "ZPP_TC_SAP_004Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP004Response")
	public void zppTCSAP004(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI004> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO004> output);

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_005", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_005:ZPP_TC_SAP_005Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_005", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP005")
	@ResponseWrapper(localName = "ZPP_TC_SAP_005Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP005Response")
	public void zppTCSAP005(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI005> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO005> output);

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_006", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_006:ZPP_TC_SAP_006Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_006", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP006")
	@ResponseWrapper(localName = "ZPP_TC_SAP_006Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP006Response")
	public void zppTCSAP006(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI006> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO006> output);

	/**
	 * 
	 * @param output
	 * @param input
	 */
	@WebMethod(operationName = "ZPP_TC_SAP_007", action = "urn:sap-com:document:sap:rfc:functions:ZPP_TC_SAP_007:ZPP_TC_SAP_007Request")
	@RequestWrapper(localName = "ZPP_TC_SAP_007", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP007")
	@ResponseWrapper(localName = "ZPP_TC_SAP_007Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "integrate.ZPPTCSAP007Response")
	public void zppTCSAP007(
            @WebParam(name = "INPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCI007> input,
            @WebParam(name = "OUTPUT", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<TABLEOFZPPTCO007> output);

}
