
package integration.base.service;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAPForTCProxy", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://service.leap.esb.com/services/SAPForTCProxy?wsdl")
public class SAPForTCProxy
    extends Service
{

    private final static URL SAPFORTCPROXY_WSDL_LOCATION;
    private final static WebServiceException SAPFORTCPROXY_EXCEPTION;
    private final static QName SAPFORTCPROXY_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://service.leap.esb.com/services/SAPForTCProxy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAPFORTCPROXY_WSDL_LOCATION = url;
        SAPFORTCPROXY_EXCEPTION = e;
    }

    public SAPForTCProxy() {
        super(__getWsdlLocation(), SAPFORTCPROXY_QNAME);
    }

    public SAPForTCProxy(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAPFORTCPROXY_QNAME, features);
    }

    public SAPForTCProxy(URL wsdlLocation) {
        super(wsdlLocation, SAPFORTCPROXY_QNAME);
    }

    public SAPForTCProxy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAPFORTCPROXY_QNAME, features);
    }

    public SAPForTCProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAPForTCProxy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpSoap11Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpSoap11Endpoint() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpSoap11Endpoint"), SAPForTCProxyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpSoap11Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpSoap11Endpoint"), SAPForTCProxyPortType.class, features);
    }

    /**
     *
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpsSoap11Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpsSoap11Endpoint() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpsSoap11Endpoint"), SAPForTCProxyPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpsSoap11Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpsSoap11Endpoint"), SAPForTCProxyPortType.class, features);
    }

    /**
     *
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpsSoap12Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpsSoap12Endpoint() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpsSoap12Endpoint"), SAPForTCProxyPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpsSoap12Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpsSoap12Endpoint"), SAPForTCProxyPortType.class, features);
    }

    /**
     *
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpSoap12Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpSoap12Endpoint() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpSoap12Endpoint"), SAPForTCProxyPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpSoap12Endpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpSoap12Endpoint"), SAPForTCProxyPortType.class, features);
    }

    /**
     *
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpEndpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpEndpoint() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpEndpoint"), SAPForTCProxyPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpEndpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpEndpoint"), SAPForTCProxyPortType.class, features);
    }

    /**
     *
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpsEndpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpsEndpoint() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpsEndpoint"), SAPForTCProxyPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPForTCProxyPortType
     */
    @WebEndpoint(name = "SAPForTCProxyHttpsEndpoint")
    public SAPForTCProxyPortType getSAPForTCProxyHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "SAPForTCProxyHttpsEndpoint"), SAPForTCProxyPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAPFORTCPROXY_EXCEPTION!= null) {
            throw SAPFORTCPROXY_EXCEPTION;
        }
        return SAPFORTCPROXY_WSDL_LOCATION;
    }

}
