
package webservice.bom;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* ZPP_TC_SAP_005 service = new ZPP_TC_SAP_005();
* ZPPTCSAP005 portType = service.getZPPTCSAP005();
* portType.zppTCSAP005(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "ZPP_TC_SAP_005", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_005.wsdl")
public class ZPPTCSAP005_Service extends Service {

	private final static URL ZPPTCSAP005_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(webservice.bom.ZPPTCSAP005_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.bom.ZPPTCSAP005_Service.class.getResource(".");
			url = new URL(baseUrl,
					"file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_005.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_005.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ZPPTCSAP005_WSDL_LOCATION = url;
	}

	public ZPPTCSAP005_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZPPTCSAP005_Service() {
		super(ZPPTCSAP005_WSDL_LOCATION, new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_005"));
	}

	/**
	 * 
	 * @return returns ZPPTCSAP005
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_005")
	public ZPPTCSAP005 getZPPTCSAP005() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_005"), ZPPTCSAP005.class);
	}

	/**
	 * 
	 * @return returns ZPPTCSAP005
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_005_soap12")
	public ZPPTCSAP005 getZPPTCSAP005Soap12() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_005_soap12"),
				ZPPTCSAP005.class);
	}

}
