
package webservice.productAttributes;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* ZPP_TC_SAP_007 service = new ZPP_TC_SAP_007();
* ZPPTCSAP007 portType = service.getZPPTCSAP007();
* portType.zppTCSAP007(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "ZPP_TC_SAP_007", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_007.wsdl")
public class ZPPTCSAP007_Service extends Service {

	private final static URL ZPPTCSAP007_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(webservice.productAttributes.ZPPTCSAP007_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.productAttributes.ZPPTCSAP007_Service.class.getResource(".");
			url = new URL(baseUrl,
					"file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_007.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_007.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ZPPTCSAP007_WSDL_LOCATION = url;
	}

	public ZPPTCSAP007_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZPPTCSAP007_Service() {
		super(ZPPTCSAP007_WSDL_LOCATION, new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_007"));
	}

	/**
	 * 
	 * @return returns ZPPTCSAP007
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_007")
	public ZPPTCSAP007 getZPPTCSAP007() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_007"), ZPPTCSAP007.class);
	}

	/**
	 * 
	 * @return returns ZPPTCSAP007
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_007_soap12")
	public ZPPTCSAP007 getZPPTCSAP007Soap12() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_007_soap12"),
				ZPPTCSAP007.class);
	}

}
