
package webservice.classify;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* ZPP_TC_SAP_003 service = new ZPP_TC_SAP_003();
* ZPPTCSAP003 portType = service.getZPPTCSAP003();
* portType.zppTCSAP003(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "ZPP_TC_SAP_003", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_003.wsdl")
public class ZPPTCSAP003_Service extends Service {

	private final static URL ZPPTCSAP003_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(webservice.classify.ZPPTCSAP003_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.classify.ZPPTCSAP003_Service.class.getResource(".");
			url = new URL(baseUrl,
					"file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_003.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_003.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ZPPTCSAP003_WSDL_LOCATION = url;
	}

	public ZPPTCSAP003_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZPPTCSAP003_Service() {
		super(ZPPTCSAP003_WSDL_LOCATION, new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_003"));
	}

	/**
	 * 
	 * @return returns ZPPTCSAP003
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_003")
	public ZPPTCSAP003 getZPPTCSAP003() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_003"), ZPPTCSAP003.class);
	}

	/**
	 * 
	 * @return returns ZPPTCSAP003
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_003_soap12")
	public ZPPTCSAP003 getZPPTCSAP003Soap12() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_003_soap12"),
				ZPPTCSAP003.class);
	}

}
