
package webservice.base.options;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* ZPP_TC_SAP_004 service = new ZPP_TC_SAP_004();
* ZPPTCSAP004 portType = service.getZPPTCSAP004();
* portType.zppTCSAP004(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "ZPP_TC_SAP_004", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/H:/eclipseworkplace/untitled1/src/main/resources/SAPInfo/zpp_tc_sap_004.wsdl")
public class ZPPTCSAP004_Service extends Service {

	private final static URL ZPPTCSAP004_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(webservice.base.options.ZPPTCSAP004_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.base.options.ZPPTCSAP004_Service.class.getResource("/");
			url = new URL(baseUrl,
					"../classes/SAPInfo/zpp_tc_sap_004.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location:" + url + ", retrying as a local file");
			logger.warning(e.getMessage());
		}
		ZPPTCSAP004_WSDL_LOCATION = url;
	}

	public ZPPTCSAP004_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZPPTCSAP004_Service() {
		super(ZPPTCSAP004_WSDL_LOCATION, new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_004"));
	}

	/**
	 * 
	 * @return returns ZPPTCSAP004
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_004")
	public ZPPTCSAP004 getZPPTCSAP004() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_004"), ZPPTCSAP004.class);
	}

	/**
	 * 
	 * @return returns ZPPTCSAP004
	 */
	@WebEndpoint(name = "ZPP_TC_SAP_004_soap12")
	public ZPPTCSAP004 getZPPTCSAP004Soap12() {
		return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZPP_TC_SAP_004_soap12"),
				ZPPTCSAP004.class);
	}

}
